version: 0.0.{build}

image: Visual Studio 2013

before_build:
  - cd "%APPVEYOR_BUILD_FOLDER%"
  - copy appveyor_programs.prop programs.prop
  - call versions.cmd
  - set GENERATOR="Visual Studio 12 2013 Win64"
  - set SGEN="vs2013-x64"

build_script:
  - msbuild /nologo /target:geos-build iricdev.proj

test_script:
  - cd "%APPVEYOR_BUILD_FOLDER%"
  - dir /s

artifacts:
  - path: lib\install
