version: 0.0.{build}

image: Visual Studio 2013

clone_folder: C:\iricdev_2013

# Note mkdir is from Git (C:\Program Files\Git\usr\bin\mkdir.exe)
# It might give unexpected results
before_build:
  - call C:\Qt\5.5\msvc2013_64\bin\qtenv2.bat
  - call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86_amd64
  - cd "%APPVEYOR_BUILD_FOLDER%"
  - copy appveyor_programs.prop programs.prop
  - call versions.cmd
  - set GENERATOR="Visual Studio 12 2013 Win64"
  - set SGEN="vs2013-x64"
  - set BUILD_TOOLS=OFF

build_script:
  - msbuild /nologo /verbosity:minimal /target:cgnslib-build-release iricdev.proj

after_build:
  - md logs
  - if exist *.log copy *.log logs\.

test_script:
  - cd "%APPVEYOR_BUILD_FOLDER%"

on_failure:
  - cd "%APPVEYOR_BUILD_FOLDER%"
  - dir /s lib\install

artifacts:
  - path: lib\install
  - path: logs

cache:
  - lib\install
