version: 0.0.{build}

image: Visual Studio 2013

clone_folder: C:\iricdev_2013

# Note mkdir is from Git (C:\Program Files\Git\usr\bin\mkdir.exe)
# It might give unexpected results
before_build:
  - call C:\Qt\5.5\msvc2013_64\bin\qtenv2.bat
  - call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86_amd64
  - cd "%APPVEYOR_BUILD_FOLDER%"
  - copy appveyor_programs.prop programs.prop
  - call versions.cmd
  - set GENERATOR="Visual Studio 12 2013 Win64"
  - set SGEN="vs2013-x64"
  - if NOT EXIST lib\install\proj-%PROJ_VER% md lib\install\proj-%PROJ_VER%

build_script:
  - msbuild /nologo /verbosity:minimal /target:proj-build iricdev.proj
  - path

after_build:
  - md logs
  - if exist *.log copy *.log logs\.

test_script:
  - cd "%APPVEYOR_BUILD_FOLDER%"
  - msbuild /nologo /target:dump iricdev.proj

artifacts:
  - path: lib\install
  - path: logs
