version: 0.0.0.2

image: Visual Studio 2013

before_build:
  - cd "%APPVEYOR_BUILD_FOLDER%"
  - copy appveyor_programs.prop programs.prop
  - call versions.cmd
  - set GENERATOR="Visual Studio 12 2013 Win64"
  - set SGEN="vs2013-x64"

build_script:
  - set
  - where curl
  - msbuild /nologo /target:netcdf-src iricdev.proj
  - dir /s
